<?php

namespace ContainerTTq5HRL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAccountPasswordControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\AccountPasswordController' shared autowired service.
     *
     * @return \App\Controller\AccountPasswordController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\AccountPasswordController'] = $instance = new \App\Controller\AccountPasswordController(($container->privates['security.user_password_hasher'] ?? $container->load('getSecurity_UserPasswordHasherService')));

        $instance->setContainer(($container->privates['.service_locator.W9y3dzm'] ?? $container->load('get_ServiceLocator_W9y3dzmService'))->withContext('App\\Controller\\AccountPasswordController', $container));

        return $instance;
    }
}
