<?php

namespace ContainerTTq5HRL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLoginFormAuthAuthenticatorService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Security\LoginFormAuthAuthenticator' shared autowired service.
     *
     * @return \App\Security\LoginFormAuthAuthenticator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Security\\LoginFormAuthAuthenticator'] = new \App\Security\LoginFormAuthAuthenticator(($container->services['router'] ?? $container->getRouterService()));
    }
}
