<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTTq5HRL\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTTq5HRL/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerTTq5HRL.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerTTq5HRL\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerTTq5HRL\App_KernelProdContainer([
    'container.build_hash' => 'TTq5HRL',
    'container.build_id' => 'd0d0977f',
    'container.build_time' => 1639665686,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTTq5HRL');
