<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'account' => [[], ['_controller' => 'App\\Controller\\AccountController::account'], [], [['text', '/account']], [], []],
    'account_password' => [[], ['_controller' => 'App\\Controller\\AccountPasswordController::passwordReset'], [], [['text', '/account/password_reset']], [], []],
    'admin' => [[], ['_controller' => 'App\\Controller\\Admin\\DashboardController::index'], [], [['text', '/admin']], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\HomeController::homePage'], [], [['text', '/']], [], []],
    'products' => [[], ['_controller' => 'App\\Controller\\ProductController::productView'], [], [['text', '/product']], [], []],
    'register' => [[], ['_controller' => 'App\\Controller\\RegisterController::register'], [], [['text', '/register']], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], []],
];
