<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerITU8DmG\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerITU8DmG/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerITU8DmG.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerITU8DmG\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerITU8DmG\App_KernelDevDebugContainer([
    'container.build_hash' => 'ITU8DmG',
    'container.build_id' => '6ae39ee7',
    'container.build_time' => 1639666724,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerITU8DmG');
